"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { FaArrowRight, FaBrain, FaExclamationTriangle, FaImage, FaRedo, FaShieldAlt } from "react-icons/fa";
import { useAuth } from "@/lib/context/AuthContext";
import { AIImageAnalysis, AIOverview, analyzeInventoryImage, askAIInventoryQuestion, getAIImageHistory, getAIOverview, refreshAIOverview } from "@/lib/api/ai-inventory";

const cards = ["critical", "lowStock", "outOfStock", "overstock", "slowMoving", "estimatedRestockQuantity"] as const;
const labels: Record<string, string> = { critical: "Critical alerts", lowStock: "Low stock", outOfStock: "Out of stock", overstock: "Overstock", slowMoving: "Slow moving", estimatedRestockQuantity: "Suggested restock units" };
const suggestedQuestions = ["How can low stock products be recovered?", "Which products should be reordered first?", "Which stock is moving slowly and what should I do?", "What inventory issues need immediate attention?"];

export default function AIInventoryView() {
  const { user } = useAuth();
  const [data, setData] = useState<AIOverview | null>(null);
  const [history, setHistory] = useState<AIImageAnalysis[]>([]);
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const [imageText, setImageText] = useState(""); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [asking, setAsking] = useState(false); const [questionError, setQuestionError] = useState("");
  const input = useRef<HTMLInputElement>(null);

  const load = async (force = false) => { try { setError(""); const [overview, images] = await Promise.all([force ? refreshAIOverview() : getAIOverview(), getAIImageHistory()]); setData(overview.data); setHistory(images.data); } catch (err: any) { setError(err.message || "Could not load inventory analysis."); } finally { setLoading(false); setRefreshing(false); } };
  useEffect(() => { void load(); }, []);
  const ask = async (event: FormEvent) => { event.preventDefault(); if (!question.trim()) return; try { setAsking(true); setQuestionError(""); setAnswer(""); const result = await askAIInventoryQuestion(question.trim()); setAnswer(result.data.answer); } catch (err: any) { setQuestionError(err.message || "Could not get an AI answer."); } finally { setAsking(false); } };
  const uploadImage = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { setImageText("Analyzing and saving image..."); const result = await analyzeInventoryImage(file); setImageText(result.data.observation); setHistory(current => [result.data, ...current].slice(0, 12)); } catch (err: any) { setImageText(err.message || "Image analysis is unavailable."); } finally { event.target.value = ""; } };
  const imageUrl = (image: string) => (process.env.NEXT_PUBLIC_API_URL || "http://localhost:8089/api/v1").replace("/api/v1", "") + image;
  if (loading) return <div className="p-12 text-center text-gray-400">Preparing inventory analysis...</div>;

  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[2px] text-purple-400">Gemini-assisted inventory intelligence</p><h1 className="mt-1 flex items-center gap-3 text-3xl font-extrabold text-white"><FaBrain className="text-purple-400" />AI Inventory Analysis</h1></div>{user?.role === "admin" && <button disabled={refreshing} onClick={() => { setRefreshing(true); void load(true); }} className="rounded-xl bg-purple-600 px-5 py-3 text-sm font-bold text-white hover:bg-purple-500 disabled:opacity-50"><FaRedo className="mr-2 inline" />{refreshing ? "Refreshing..." : "Refresh analysis"}</button>}</div>
    {error ? <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error} <button onClick={() => void load()} className="underline">Retry</button></div> : data && <>
      <section className="rounded-3xl border border-purple-500/25 bg-gradient-to-br from-purple-950/50 to-slate-900/70 p-6"><h2 className="flex items-center gap-2 font-bold text-white"><FaBrain className="text-purple-300" />Ask Inventory AI</h2><p className="mt-1 text-xs text-gray-400">Ask about the current calculated stock, demand and restocking recommendations.</p><form onSubmit={ask} className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={question} onChange={event => setQuestion(event.target.value)} maxLength={600} placeholder="Example: How can low stock products be recovered?" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-white outline-none focus:border-purple-400" /><button disabled={asking || !question.trim()} className="rounded-xl bg-purple-600 px-5 py-3 text-sm font-bold text-white hover:bg-purple-500 disabled:opacity-50">{asking ? "Thinking..." : "Ask AI"} <FaArrowRight className="ml-1 inline" /></button></form><div className="mt-4 grid gap-2 sm:grid-cols-2">{suggestedQuestions.map(item => <button key={item} type="button" onClick={() => { setQuestion(item); setAnswer(""); setQuestionError(""); }} className="rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2 text-left text-xs text-purple-200 hover:bg-purple-500/10">{item}</button>)}</div>{questionError && <p className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{questionError}</p>}{answer && <div className="mt-4 rounded-2xl border border-purple-400/20 bg-slate-950/60 p-4"><p className="text-xs font-bold uppercase tracking-wider text-purple-300">AI answer</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-gray-200">{answer}</p></div>}</section>
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-6">{cards.map(key => <div key={key} className="rounded-2xl border border-white/5 bg-slate-900/60 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-gray-500">{labels[key]}</p><p className="mt-2 text-2xl font-black text-white">{data.deterministic[key]}</p></div>)}</div>
      <section className="rounded-3xl border border-purple-500/20 bg-[#1e293b]/70 p-6"><div className="flex items-center gap-2 text-purple-300"><FaShieldAlt /><span className="text-sm font-bold uppercase tracking-wider">Risk: {data.analysis.overallRisk}</span></div><p className="mt-3 text-sm leading-6 text-gray-200">{data.analysis.summary}</p><p className="mt-4 text-xs text-gray-500">Generated {new Date(data.analysis.generatedAt).toLocaleString()} · {data.fallbackUsed ? "Deterministic fallback: AI explanation unavailable." : data.cached ? "Cached analysis." : "Fresh analysis."} Recommendations require human review.</p></section>
      <section className="rounded-3xl border border-white/5 bg-slate-900/50 p-6"><h2 className="flex items-center gap-2 font-bold text-white"><FaExclamationTriangle className="text-amber-400" />Products requiring attention</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-gray-500"><tr><th className="p-2">Product</th><th>Alert</th><th>Risk</th><th>Stock</th><th>Days</th><th>Reorder</th><th>Action</th></tr></thead><tbody>{data.analysis.urgentProducts.map(item => <tr key={`${item.productId}-${item.alertType}`} className="border-t border-white/5 text-gray-300"><td className="p-2 font-bold text-white">{item.productName}</td><td>{item.alertType.replaceAll("_", " ")}</td><td className="uppercase">{item.riskLevel}</td><td>{data.alerts.find((alert: any) => alert.productId === item.productId)?.currentStock ?? "—"}</td><td>{item.estimatedDaysRemaining ?? "—"}</td><td>{item.recommendedReorderQuantity}</td><td>{item.recommendedAction}</td></tr>)}</tbody></table>{!data.analysis.urgentProducts.length && <p className="py-8 text-center text-sm text-gray-500">No active deterministic inventory alerts.</p>}</div></section>
      <section className="rounded-3xl border border-white/5 bg-slate-900/50 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-white">Saved image analysis</h2><p className="mt-1 text-xs text-gray-500">Upload a stock-shelf or product image. Gemini provides a descriptive review; it never changes inventory.</p></div><input ref={input} className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={uploadImage} /><button onClick={() => input.current?.click()} className="rounded-xl border border-white/10 px-4 py-2 text-xs font-bold text-white hover:bg-white/5"><FaImage className="mr-2 inline" />Upload & analyze</button></div>{imageText && <p className="mt-4 rounded-xl bg-white/5 p-4 text-sm text-gray-300">{imageText}</p>}{history.length > 0 && <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{history.map(item => <article key={item.id || item._id} className="overflow-hidden rounded-2xl border border-white/5 bg-white/[0.03]"><img src={imageUrl(item.image)} alt="Inventory analysis upload" className="h-36 w-full object-cover" /><div className="p-4"><p className="text-sm leading-6 text-gray-300">{item.observation}</p><p className="mt-3 text-[10px] text-gray-500">{new Date(item.createdAt).toLocaleString()}</p></div></article>)}</div>}</section>
    </>}
  </div>;
}
