import mongoose from "mongoose";
import { AIAnalysisLogModel } from "../models/ai-analysis-log.model";
import { InventoryAlertModel } from "../models/inventory-alert.model";
import { InventoryAnalyticsService } from "./inventory-analytics.service";
import { GeminiService } from "./gemini.service";
import { AIInventoryAnalysis } from "../schemas/ai-inventory.schema";
import { AIImageAnalysisModel } from "../models/ai-image-analysis.model";
import { Express } from "express";
import fs from "fs";

export class AIInventoryService {
 private analytics=new InventoryAnalyticsService(); private gemini=new GeminiService();
 private fallback(data:any):AIInventoryAnalysis { const urgent=data.attention.slice(0,20).map((m:any)=>({productId:m.productId,productName:m.productName,riskLevel:m.riskLevel,alertType:m.alertType,estimatedDaysRemaining:m.estimatedDaysRemaining,recommendedReorderQuantity:m.recommendedReorderQuantity,reason:"Deterministic stock and sales calculation.",recommendedAction:m.recommendedReorderQuantity?`Review and reorder ${m.recommendedReorderQuantity} units.`:"Review inventory status."})); return {generatedAt:data.generatedAt,summary:"AI explanation is temporarily unavailable. Stock calculations are still current.",overallRisk:urgent.some((m:any)=>m.riskLevel==="critical")?"critical":urgent.some((m:any)=>m.riskLevel==="high")?"high":"low",urgentProducts:urgent,insights:urgent.length?[{title:"Inventory review needed",description:`${urgent.length} products need attention based on deterministic calculations.`,priority:"high"}]:[{title:"Inventory stable",description:"No deterministic stock alerts are active.",priority:"low"}]}; }
 async overview(userId:string, force=false) { const minutes=Number(process.env.GEMINI_ANALYSIS_CACHE_MINUTES||60); if(!force){const cached=await AIAnalysisLogModel.findOne({expiresAt:{$gt:new Date()}}).sort({createdAt:-1}); if(cached) return {...(cached.result as any), cached:true};} const started=Date.now(); const deterministic=await this.analytics.calculate(); let analysis:AIInventoryAnalysis, succeeded=false; try { const max=Number(process.env.GEMINI_MAX_PRODUCTS_PER_REQUEST||50); analysis=await this.gemini.analyze({analysisPeriodDays:30,forecastDays:14,products:deterministic.metrics.slice(0,max)}); succeeded=true; } catch { analysis=this.fallback(deterministic); } const result={deterministic:deterministic.summary,analysis,alerts:deterministic.attention,forecastDays:14,fallbackUsed:!succeeded,cached:false}; await AIAnalysisLogModel.create({requestedBy:new mongoose.Types.ObjectId(userId),model:process.env.GEMINI_MODEL||"gemini-2.5-flash",productCount:deterministic.metrics.length,aiSucceeded:succeeded,fallbackUsed:!succeeded,durationMs:Date.now()-started,result,expiresAt:new Date(Date.now()+minutes*60000)}); return result; }
 async alerts(query:any){ const filter:any={status:query.status||"active"}; if(query.severity)filter.severity=query.severity;if(query.type)filter.alertType=query.type; const page=Math.max(1,Number(query.page)||1),limit=Math.min(50,Math.max(1,Number(query.limit)||20)); const [items,total]=await Promise.all([InventoryAlertModel.find(filter).populate("productId","name category").sort({severity:1,generatedAt:-1}).skip((page-1)*limit).limit(limit),InventoryAlertModel.countDocuments(filter)]); return {items,page,limit,total}; }
 async forecast(days:number){const data=await this.analytics.calculate();return data.metrics.map(metric=>({productId:metric.productId,productName:metric.productName,currentStock:metric.currentStock,averageDailySales:metric.averageDailySales,forecastDemand:days===7?metric.forecast7:days===14?metric.forecast14:metric.forecast30,estimatedDaysRemaining:metric.estimatedDaysRemaining,recommendedReorderQuantity:metric.recommendedReorderQuantity,riskLevel:metric.riskLevel}));}
 async product(id:string){const data=await this.analytics.calculate();return data.metrics.find(metric=>metric.productId===id)||null;}
 async image(userId:string,file:Express.Multer.File){let observation="Image saved successfully. Add a Gemini API key to generate an inventory observation.";let aiAvailable=false;try{observation=await this.gemini.analyzeImage(fs.readFileSync(file.path),file.mimetype);aiAvailable=true;}catch{}const saved=await AIImageAnalysisModel.create({userId,image:`/uploads/ai-analysis/${file.filename}`,observation});return {id:saved._id,image:saved.image,observation:saved.observation,aiAvailable,createdAt:saved.createdAt};}
 async imageHistory(userId:string){return AIImageAnalysisModel.find({userId}).sort({createdAt:-1}).limit(12).select("image observation createdAt").lean();}
 async question(question:string){const deterministic=await this.analytics.calculate();const data={summary:deterministic.summary,products:deterministic.metrics.slice(0,Number(process.env.GEMINI_MAX_PRODUCTS_PER_REQUEST||50)),attention:deterministic.attention.slice(0,20)};return {answer:await this.gemini.answerInventoryQuestion(question,data),generatedAt:new Date().toISOString()};}
}
