import { OrderModel } from "../models/order.model";
import { ProductModel } from "../models/product.model";
import { InventoryAlertModel } from "../models/inventory-alert.model";

export interface ProductMetric { productId: string; productName: string; category: string; currentStock: number; reorderLevel: number; averageDailySales: number; forecast7: number; forecast14: number; forecast30: number; estimatedDaysRemaining: number|null; recommendedReorderQuantity: number; riskLevel: "low"|"medium"|"high"|"critical"; alertType?: "low_stock"|"out_of_stock"|"stock_out_risk"|"overstock"|"slow_moving"; }
const safeText = (value: string) => value.replace(/[\r\n\u0000]/g, " ").slice(0, 120);
export class InventoryAnalyticsService {
 async calculate() {
  const since30 = new Date(Date.now() - 30*86400000); const since7 = new Date(Date.now() - 7*86400000);
  const [products, orders30, orders7] = await Promise.all([ProductModel.find(), OrderModel.find({ createdAt: { $gte: since30 }, status: { $ne: "cancelled" } }).select("items createdAt"), OrderModel.find({ createdAt: { $gte: since7 }, status: { $ne: "cancelled" } }).select("items")]);
  const sum = (orders: any[], id: string) => orders.reduce((total, order) => total + order.items.filter((item: any) => item.productId === id).reduce((n: number, item: any) => n + item.quantity, 0), 0);
  const metrics: ProductMetric[] = products.map(product => { const sold30=sum(orders30,product._id.toString()), sold7=sum(orders7,product._id.toString()); const daily=sold30/30; const forecast14=Math.ceil(Math.max(daily,(sold7/7)*0.65+daily*0.35)*14); const days=daily>0?Number((product.quantity/daily).toFixed(1)):null; const reorder=Math.max(0,forecast14+Math.ceil(daily*3)-product.quantity); let risk: ProductMetric["riskLevel"]="low", type: ProductMetric["alertType"]; if(product.quantity===0){risk="critical";type="out_of_stock";} else if(days!==null&&days<=3){risk="critical";type="stock_out_risk";} else if(product.quantity<=product.lowStockThreshold){risk="high";type="low_stock";} else if(daily===0&&product.quantity>product.lowStockThreshold*3){risk="medium";type="slow_moving";} else if(days!==null&&days>90){risk="medium";type="overstock";} return { productId:product._id.toString(),productName:safeText(product.name),category:safeText(product.category),currentStock:product.quantity,reorderLevel:product.lowStockThreshold,averageDailySales:Number(daily.toFixed(2)),forecast7:Math.ceil(forecast14/2),forecast14,forecast30:Math.ceil(forecast14*30/14),estimatedDaysRemaining:days,recommendedReorderQuantity:reorder,riskLevel:risk,alertType:type}; });
  const attention=metrics.filter(m=>m.alertType); await Promise.all(attention.map(m=>InventoryAlertModel.findOneAndUpdate({productId:m.productId,alertType:m.alertType,status:"active"},{ $set:{severity:m.riskLevel,title:`${m.productName}: ${m.alertType!.replaceAll("_"," ")}`,message:`Stock ${m.currentStock}; recommended reorder ${m.recommendedReorderQuantity}.`,currentStock:m.currentStock,reorderLevel:m.reorderLevel,estimatedDaysRemaining:m.estimatedDaysRemaining,recommendedReorderQuantity:m.recommendedReorderQuantity,source:"system",generatedAt:new Date()}},{upsert:true,new:true,setDefaultsOnInsert:true})));
  return { generatedAt:new Date().toISOString(), metrics, summary:{ totalActiveProducts:products.length, lowStock:metrics.filter(m=>m.alertType==="low_stock").length, outOfStock:metrics.filter(m=>m.alertType==="out_of_stock").length, critical:metrics.filter(m=>m.riskLevel==="critical").length, overstock:metrics.filter(m=>m.alertType==="overstock").length, slowMoving:metrics.filter(m=>m.alertType==="slow_moving").length, inventoryValue:products.reduce((n,p)=>n+p.price*p.quantity,0), estimatedRestockQuantity:metrics.reduce((n,m)=>n+m.recommendedReorderQuantity,0) }, attention };
 }
}
